import type { PersonCard, SocialEffect } from '../types';

/*
 * The building's people (docs/building.md, docs/social.md): the residents behind the doors on the stairs (`door`:
 * `stairwell/building.doorKey(k, i)`), the concierge, the syndic, the attic's student, the postman, Lambert's niece.
 * Their effects' keys are read by the building's systems through `social/perks.effect`.
 */

/**
 * A resident with a door has a vote at the co-owners' meeting, and how the player stands with them sways it
 * (`building/coproSway`): these effects say so in the book and are what the sway reads.
 */
const VOTE_EFFECTS: readonly SocialEffect[] = [
  { key: 'votesWithYou', at: 'friend', text: 'Votes with you at the co-owners’ meeting' },
  { key: 'lobbies', at: 'close', text: 'Brings another resident round to your vote' },
  { key: 'votesAgainst', at: 'hostile', down: true, text: 'Votes against you at the co-owners’ meeting' },
];

function withVotes(cards: readonly PersonCard[]): readonly PersonCard[] {
  return cards.map((c) => (c.door ? { ...c, effects: [...(c.effects ?? []), ...VOTE_EFFECTS] } : c));
}

export const BUILDING_PEOPLE: readonly PersonCard[] = withVotes([
  {
    id: 'roux',
    name: 'Hélène Roux',
    short: 'Mrs Roux',
    role: '5th floor, across the landing',
    group: 'building',
    door: '0:0',
    whereabouts: 'Home most of the day; on the stairs, slowly, mid-morning',
    intro: 'Hélène Roux. I have lived across the landing from your flat since 1971. You are the one with all the little boxes.',
    traits: ['nostalgic', 'chatty', 'catPerson'],
    likes: ['flowers', 'cake', 'croissant'],
    dislikes: ['coins'],
    birthday: 4,
    look: { seed: 11 + 900, role: 'shopper' },
    phone: true,
    ties: { moreau: 0.5, pereira: 0.6, dubois: 0.3 },
    facts: [
      { id: 'husband', text: 'Widowed; her husband Lucien repaired radios', says: 'Lucien, my husband, mended radios. The flat still smells of solder when it rains.' },
      { id: 'daughter', text: 'Her daughter lives in Lyon', says: 'My daughter wants me in Lyon. Lyon! I ask you.', from: 'acquaintance' },
      { id: 'stairs', text: 'The stairs are getting hard for her', says: 'Five floors. Every year they add a step, I am sure of it.', from: 'friendly' },
      { id: 'lucienGames', text: 'Lucien kept a box of games for the grandchildren', says: 'Lucien bought games for the grandson. A whole box, in the wardrobe. Nobody plays them.', from: 'friend' },
    ],
    effects: [
      { key: 'stories', at: 'friendly', text: 'Tells you the building’s old stories (clues for the hunt and the prototype)' },
      { key: 'lucienGames', at: 'friend', trust: 30, text: 'Gives you Lucien’s box of games before she moves' },
      { key: 'annexDiscount', at: 'close', value: 0.8, text: 'Sells you her flat for less (0.8 of the price)' },
      { key: 'curtAtDoor', at: 'cold', down: true, text: 'No more chats at her door' },
    ],
    lines: {
      hello: ['Good morning, dear.', 'Ah, there you are.', 'Mind the step, dear.'],
      chat: ['In 1971 the stairs were waxed every Friday. You could skate down them.', 'The light on our landing goes out too fast. It never used to.', 'Your cat sat outside my door this morning. We had a little talk.'],
      cold: ['Hm.', 'Good day.'],
      hostile: ['I have nothing to say to you.'],
    },
    startWarmth: 5,
  },
  {
    id: 'moreau',
    name: 'Claudine & Paul Moreau',
    short: 'the Moreaus',
    role: '4th floor, left (the piano)',
    group: 'building',
    door: '1:0',
    whereabouts: 'Out 8:00 to 18:30; the piano in the evening',
    intro: 'Claudine Moreau, and Paul is the one carrying the bags. We are right under you. You will have heard the piano.',
    traits: ['generous', 'catPerson', 'earlyBird'],
    likes: ['cake', 'flowers', 'record'],
    dislikes: ['scrap'],
    birthday: 17,
    look: { seed: 23 + 900, role: 'shopper' },
    phone: true,
    ties: { roux: 0.5, leclerc: 0.3, nguyen: 0.4 },
    facts: [
      { id: 'piano', text: 'Claudine teaches piano', says: 'I teach piano, at the conservatoire. Then I come home and play more piano. Paul is a saint.' },
      { id: 'son', text: 'Their son loves old video games', says: 'Our son, Hugo, loves those old games. He would spend his life on your sofa if we let him.', from: 'acquaintance' },
      { id: 'photo', text: 'Their wedding photo was taken in front of an arcade cabinet', says: 'Our wedding photo? In front of a pinball, in a café in Nantes. Paul lost every game that night.', from: 'friend' },
    ],
    effects: [
      { key: 'quietPiano', at: 'friendly', text: 'Plays the piano softer' },
      { key: 'catSitter', at: 'friend', trust: 35, text: 'Keeps your spare key and feeds the cat while you are out' },
      { key: 'sundayLunch', at: 'close', text: 'Sunday lunch at theirs: their game on their TV, two players' },
      { key: 'loudPiano', at: 'hostile', down: true, text: 'Practises scales right under you, late' },
    ],
    lines: {
      hello: ['Hello, neighbour!', 'Oh, hi!', 'Evening!'],
      chat: ['Paul has decided to learn the guitar. Pray for us all.', 'Hugo asked if you had “the one with the plumber”. I said you had all of them.', 'The cat came down our stairs again. We gave it some ham. Don’t tell.'],
    },
  },
  {
    id: 'leclerc',
    name: 'Alain Leclerc',
    short: 'Mr Leclerc',
    role: '4th floor, right (under your living room)',
    group: 'building',
    door: '1:1',
    whereabouts: 'Up at six, in bed by ten. Always in.',
    intro: 'Leclerc. Under your living room. I go to bed at ten. I mention it in passing.',
    traits: ['grumpy', 'neat', 'earlyBird', 'proud'],
    likes: ['croissant', 'coffee'],
    dislikes: ['plush', 'game'],
    birthday: 31,
    look: { seed: 131, role: 'shopper' },
    ties: { student: -0.6, moreau: 0.3, bertin: 0.5, pereira: 0.2 },
    facts: [
      { id: 'railway', text: 'Retired railway signalman', says: 'Forty years on the signals at Austerlitz. I know what a timetable is for.' },
      { id: 'sleep', text: 'Sleeps badly since his wife died', says: 'I don’t sleep, since Mireille. So I hear everything. Everything.', from: 'friendly' },
      { id: 'trains', text: 'Secretly loves train games', says: 'There was a game with trains. You built the lines yourself. Don’t tell anyone.', from: 'friend' },
    ],
    effects: [
      { key: 'noiseThreshold', at: 'friendly', value: 0.5, text: 'Puts up with more noise at night' },
      { key: 'noiseFrom', at: 'friend', value: 23, text: 'Doesn’t mind noise before eleven' },
      { key: 'noComplaints', at: 'close', text: 'Never complains about noise: comes up to listen to your game instead' },
      { key: 'noiseFrom', at: 'cold', down: true, value: 21, text: 'Complains about noise from nine' },
      { key: 'straightToSyndic', at: 'hostile', down: true, text: 'Goes straight to the syndic' },
      { key: 'feud', at: 'nemesis', down: true, text: 'Feuds with you: notes on the board, his radio through your floor' },
    ],
    lines: {
      hello: ['Morning.', 'Hm. Hello.', 'Evening.'],
      chat: ['The bins went out late again. Not you. I am only saying.', 'Ten o’clock. I go to bed at ten.', 'Someone left a bicycle in the hall. A bicycle!'],
      cold: ['Hm.', 'I know it was you.'],
      hostile: ['Don’t.', 'I have written to the syndic.'],
    },
    startWarmth: -5,
  },
  {
    id: 'nguyen',
    name: 'Linh & Bao Nguyen',
    short: 'the Nguyens',
    role: '3rd floor, left',
    group: 'building',
    door: '2:0',
    whereabouts: 'Out 8:30 to 18:00; their twins on the stairs after school',
    intro: 'Linh Nguyen, hi! The twins are ours, sorry in advance. Bao is at work, he is always at work.',
    traits: ['funny', 'generous', 'chatty'],
    likes: ['cake', 'plush', 'treats'],
    dislikes: ['coins'],
    birthday: 44,
    look: { seed: 23, role: 'shopper' },
    phone: true,
    ties: { moreau: 0.4, rossi: 0.3, girard: 0.2 },
    facts: [
      { id: 'twins', text: 'Twins, eight, both mad about platformers', says: 'The twins? Eight. They fight over one controller like it’s the last lifeboat.' },
      { id: 'restaurant', text: 'Bao runs a restaurant on Front Street', says: 'Bao’s restaurant is the one with the red lanterns. Say my name, you get spring rolls.', from: 'acquaintance' },
      { id: 'pad', text: 'They have a spare pad nobody uses', says: 'We have a spare controller, the twins broke the other one fighting over it.', from: 'friendly' },
    ],
    effects: [
      { key: 'lendsPad', at: 'friend', text: 'Lends you a second pad for games nights' },
      { key: 'familyDinner', at: 'close', text: 'Dinner at theirs, the twins against you' },
    ],
  },
  {
    id: 'girard',
    name: 'Pascal Girard',
    short: 'Pascal',
    role: '3rd floor, right',
    group: 'building',
    door: '2:1',
    whereabouts: 'Out 7:30 to 19:00, running up the stairs',
    intro: 'Pascal. Third floor. I run up the stairs: it’s my gym. You should try it.',
    traits: ['competitive', 'funny'],
    likes: ['coffee', 'croissant'],
    dislikes: ['cake'],
    birthday: 52,
    look: { seed: 37 + 900, role: 'shopper' },
    phone: true,
    ties: { rossi: 0.4, dubois: -0.3, martin: 0.3 },
    facts: [
      { id: 'gameboy', text: 'Lost his Game Boy in 1994 and still mourns it', says: 'My Game Boy. 1994. Left it on a train. I still dream of it.' },
      { id: 'removals', text: 'Moves furniture for a living', says: 'I move furniture for a living. Pianos. Don’t tell the Moreaus.', from: 'acquaintance' },
    ],
    effects: [
      { key: 'helpsCarry', at: 'friend', text: 'Helps you carry heavy furniture (moved in one go)' },
      { key: 'stairsRace', at: 'friendly', text: 'Races you up the stairs (and pays up when he loses)' },
    ],
  },
  {
    id: 'haddad',
    name: 'Rania Haddad',
    short: 'Mrs Haddad',
    role: '2nd floor, left (the swaps)',
    group: 'building',
    door: '3:0',
    whereabouts: 'Out 10:00 to 20:00; swaps games on her doorstep',
    intro: 'Rania Haddad. Second floor. I collect too, a little. Mostly Sega. We will get on, or we will be rivals.',
    traits: ['collector', 'nostalgic', 'proud'],
    tastes: { platforms: ['megadrive', 'mastersystem', 'saturn', 'gamegear'], genres: ['platform', 'action'] },
    likes: ['game', 'record', 'coffee'],
    dislikes: ['treats'],
    birthday: 9,
    look: { seed: 41 + 900, role: 'shopper' },
    phone: true,
    ties: { dubois: 0.7, martin: 0.5, victor: -0.4 },
    facts: [
      { id: 'sega', text: 'A Sega collector', says: 'Sega, always Sega. Nintendo was for children who did their homework.' },
      { id: 'vasseur', text: 'Knew old Vasseur, who lived in the attic', says: 'Vasseur? He lived in the attic. He scratched something in the lift, they say.', from: 'friendly' },
      { id: 'victor', text: 'Cannot stand Victor Crane', says: 'Victor Crane outbid me on a sealed Sonic in 2009. I have not forgiven him.', from: 'friend' },
    ],
    effects: [
      { key: 'betterSwaps', at: 'friendly', text: 'Her swaps ask less of you' },
      { key: 'lore', at: 'friend', text: 'Tells you what Vasseur hid in the building' },
      { key: 'sharesFinds', at: 'close', text: 'Puts a Sega game aside for you now and then' },
    ],
  },
  {
    id: 'dubois',
    name: 'Simone Dubois',
    short: 'Mrs Dubois',
    role: '2nd floor, right',
    group: 'building',
    door: '3:1',
    whereabouts: 'Out mid-morning to the market; home by eight',
    intro: 'Simone Dubois, second floor. And you are the collector. Oh, everybody knows, dear.',
    traits: ['gossip', 'romantic', 'chatty'],
    likes: ['flowers', 'cake', 'croissant'],
    dislikes: ['scrap', 'game'],
    birthday: 23,
    look: { seed: 59 + 900, role: 'shopper' },
    phone: true,
    ties: { haddad: 0.7, pereira: 0.4, girard: -0.3, roux: 0.3, rossi: 0.3 },
    facts: [
      { id: 'plants', text: 'Waters everyone’s plants (once)', says: 'I watered Mrs Pereira’s plants once. Once! She still talks about it.' },
      { id: 'knows', text: 'Knows everyone’s business', says: 'The Nguyens are thinking of a third. You did not hear it from me.', from: 'acquaintance' },
      { id: 'dancer', text: 'Danced at the Moulin Rouge in 1968', says: 'I danced, you know. In 1968. The things I saw.', from: 'friend' },
    ],
    effects: [
      { key: 'gossipBoard', at: 'friendly', text: 'Tells you the building’s news, and other residents’ secrets' },
      { key: 'watersPlants', at: 'friend', trust: 30, text: 'Waters your plants while you are out' },
      { key: 'badMouths', at: 'hostile', down: true, text: 'Tells the whole building about you' },
    ],
  },
  {
    id: 'martin',
    name: 'Jean-Pierre Martin',
    short: 'Mr Martin',
    role: '1st floor, left',
    group: 'building',
    door: '4:0',
    whereabouts: 'Home after lunch; plays cards in the hall when the lights go out',
    intro: 'Martin. Jean-Pierre. First floor. I keep to myself, mostly.',
    traits: ['shy', 'nostalgic'],
    tastes: { platforms: ['nes', 'gb'], era: [1985, 1993] },
    likes: ['coffee', 'record'],
    dislikes: ['flowers'],
    birthday: 38,
    look: { seed: 41, role: 'shopper' },
    ties: { haddad: 0.5, girard: 0.3 },
    facts: [
      { id: 'brother', text: 'His late brother Gilles collected NES cartridges', says: 'My brother had all of them. The grey cartridges. Gilles. He died in the spring.', from: 'acquaintance' },
      { id: 'boxes', text: 'Gilles’s cartridges are boxed in his cellar', says: 'Gilles’s cartridges are in my cellar. I can’t open the box. Maybe you could.', from: 'friend' },
    ],
    effects: [
      { key: 'brotherCarts', at: 'close', trust: 50, text: 'Gives you his brother’s cartridges, to keep together' },
      { key: 'cardsInvite', at: 'friendly', text: 'Lets you sit in at cards during a power cut' },
    ],
    startWarmth: 0,
  },
  {
    id: 'rossi',
    name: 'Sofia Rossi',
    short: 'Sofia',
    role: '1st floor, right',
    group: 'building',
    door: '4:1',
    whereabouts: 'Out 8:30 to 18:00; never takes the lift',
    intro: 'Sofia Rossi, first floor. I never take the lift. Hi!',
    traits: ['chatty', 'earlyBird', 'funny'],
    likes: ['flowers', 'coffee', 'plush'],
    dislikes: ['scrap'],
    birthday: 13,
    look: { seed: 59, role: 'shopper' },
    phone: true,
    ties: { girard: 0.4, nguyen: 0.3, dubois: 0.3 },
    facts: [
      { id: 'post', text: 'Works at the sorting office', says: 'I sort the post for the whole district. I know who gets catalogues.' },
      { id: 'arcade', text: 'Was the arcade’s champion at fourteen', says: 'I was the champion of the arcade at fourteen. Comets. Nobody believes me.', from: 'friendly' },
    ],
    effects: [
      { key: 'postNews', at: 'friendly', text: 'Tells you when a parcel is on its way' },
      { key: 'arcadeTips', at: 'friend', text: 'Coaches you at Comets (a better first ticket strip)' },
    ],
  },
  {
    id: 'pereira',
    name: 'Fernanda Pereira',
    short: 'Mme Pereira',
    role: 'the concierge',
    group: 'building',
    whereabouts: 'In her lodge 8-12 and 15-19; some mornings mopping a landing',
    intro: 'Ah, you are the new one on the fifth. Pereira, the concierge. The lodge is open mornings and afternoons.',
    traits: ['businesslike', 'neat', 'proud'],
    likes: ['flowers', 'coins', 'cake'],
    dislikes: ['plush'],
    birthday: 27,
    look: { seed: 97, role: 'shopper' },
    phone: true,
    ties: { roux: 0.6, dubois: 0.4, bertin: -0.2, leclerc: 0.2 },
    facts: [
      { id: 'porto', text: 'From Porto; goes home every August', says: 'Every August I go home to Porto. The building falls apart without me.' },
      { id: 'keys', text: 'Has a key to every door in the building', says: 'I have a key to every door. Every one. I use none of them. Mostly.', from: 'friendly' },
    ],
    effects: [
      { key: 'parcelNews', at: 'friendly', text: 'Tells you what is arriving in the post' },
      { key: 'holdsParcels', at: 'friend', text: 'Signs for your parcels: they come a round sooner' },
      { key: 'roofKey', at: 'close', trust: 50, text: 'Gives you the key to the roof' },
      { key: 'lateParcels', at: 'cold', down: true, text: 'Your parcels come a day late' },
    ],
    lines: {
      chat: ['Parcels go to your door now. The postman takes the lift, the lazy thing.', 'The light on the stairs is on a timer. Press the button, it stays on for a while.', 'Mrs Dubois watered my plants once. Once.', 'Wipe your feet. I have just done the hall.'],
    },
  },
  {
    id: 'bertin',
    name: 'Gérard Bertin',
    short: 'M. Bertin',
    role: 'the syndic',
    group: 'building',
    whereabouts: 'In the hall on the co-owners’ meeting days, 17:00-22:00',
    intro: 'Bertin, the syndic. The co-owners’ meeting is every fourteen days. Attendance is, of course, voluntary. And noted.',
    traits: ['businesslike', 'proud'],
    likes: ['coffee', 'coins'],
    dislikes: ['plush', 'treats'],
    birthday: 49,
    look: { seed: 0, role: 'shopper' },
    ties: { leclerc: 0.5, pereira: -0.2 },
    facts: [
      { id: 'minutes', text: 'Has kept every meeting’s minutes since 1988', says: 'Every minute since 1988. Bound. In my study. People laugh.' },
    ],
    effects: [
      { key: 'agendaEarly', at: 'friendly', text: 'Tells you the next agenda early' },
      { key: 'tieBreak', at: 'friend', text: 'A tie at the co-owners’ meeting goes your way' },
      { key: 'strictReminders', at: 'cold', down: true, text: 'A noise reminder costs you more with the building' },
    ],
  },
  {
    id: 'student',
    name: 'Théo Lambrini',
    short: 'Théo',
    role: 'the attic room (the music at night)',
    group: 'building',
    whereabouts: 'Up at noon; on the stairs late at night',
    intro: 'Théo. The room under the roof. Sorry about the music. Actually not that sorry.',
    traits: ['nightOwl', 'funny', 'collector'],
    tastes: { platforms: ['ps1', 'n64', 'dreamcast'], genres: ['racing', 'music'] },
    likes: ['coffee', 'record', 'croissant'],
    dislikes: ['flowers'],
    birthday: 57,
    look: { seed: 151, role: 'shopper' },
    phone: true,
    ties: { leclerc: -0.6, rossi: 0.2 },
    facts: [
      { id: 'electronics', text: 'Studies electronics; mends consoles for fun', says: 'Electronics. Third year. I recap consoles for fun. It is a sickness.' },
      { id: 'homebrew', text: 'Writes his own games for old cartridges', says: 'I write games for real cartridges. Tiny ones. I could burn you one.', from: 'friend' },
    ],
    effects: [
      { key: 'repairBonus', at: 'friend', value: 0.2, text: 'Lends you his soldering iron: repairs go better' },
      { key: 'homebrewCart', at: 'close', text: 'Burns you a homebrew cartridge for the TV' },
      { key: 'loudMusic', at: 'cold', down: true, text: 'Turns the music up some nights' },
    ],
  },
  {
    id: 'postman',
    name: 'Moussa Diallo',
    short: 'the postman',
    role: 'the postman',
    group: 'building',
    whereabouts: 'At your door with the post, mornings',
    intro: 'Diallo, the post. I come at ten, more or less. Mostly less.',
    traits: ['chatty', 'funny'],
    likes: ['coffee', 'croissant'],
    birthday: 35,
    look: { seed: 77, role: 'shopper' },
    ties: { rossi: 0.3, pereira: -0.1 },
    facts: [{ id: 'dog', text: 'Afraid of the dog on the 3rd floor', says: 'The dog on the third. Every day he waits for me. Every day.' }],
    effects: [{ key: 'carriesUp', at: 'friend', text: 'Brings big parcels right up to your door' }],
  },
  {
    id: 'claire',
    name: 'Claire Lambert',
    short: 'Claire',
    role: 'the late Mr Lambert’s niece',
    group: 'building',
    whereabouts: 'At the estate sale in the hall; after that, now and then on a visit',
    intro: 'Claire. Henri Lambert was my uncle. He would have liked you, I think. He liked people who keep things.',
    traits: ['shy', 'nostalgic'],
    likes: ['flowers', 'record'],
    birthday: 20,
    look: { seed: 113 + 900, role: 'shopper' },
    phone: true,
    ties: { roux: 0.4 },
    facts: [
      { id: 'henri', text: 'Her uncle Henri left clues all over the building', says: 'Uncle Henri loved puzzles. He hid things. We keep finding notes.', from: 'acquaintance' },
    ],
    effects: [{ key: 'claireReturns', at: 'friendly', text: 'Comes back with one of Henri’s games she kept for you' }],
  },
]);
