import type { PersonCard } from '../types';

/*
 * The player's friends from before (docs/visitors.md): Sam, Inès, Marco. Their ids are `visitors/friendsPlan`'s, so
 * a visit, a loan and a games night nudge the same standing. In the book from the start.
 */
export const FRIEND_PEOPLE: readonly PersonCard[] = [
  {
    id: 'sam',
    name: 'Sam Okoro',
    short: 'Sam',
    role: 'old friend (platformers)',
    group: 'friends',
    whereabouts: 'Comes round some afternoons; on the phone any time',
    intro: 'It’s me, Sam. Obviously.',
    traits: ['funny', 'chatty', 'catPerson'],
    tastes: { platforms: ['nes', 'snes', 'gb'], genres: ['platform', 'action', 'puzzle'], era: [1985, 1995] },
    likes: ['cake', 'croissant', 'game'],
    dislikes: ['coins'],
    birthday: 7,
    look: { seed: 311, role: 'shopper' },
    phone: true,
    ties: { ines: 0.6, marco: 0.7 },
    facts: [
      { id: 'speedrun', text: 'Speedruns Super Mario Bros. badly', says: 'My best on Mario is 5:41. Don’t laugh. Okay, laugh.' },
      { id: 'job', text: 'Works nights at a hospital', says: 'Nights at the hospital this month. Your sofa is the only place I sleep properly.', from: 'friendly' },
    ],
    effects: [
      { key: 'lendsGames', at: 'friend', text: 'Lends you games from their own shelf' },
      { key: 'helpsCarry', at: 'friend', text: 'Helps carry heavy furniture' },
      { key: 'dropsBy', at: 'close', text: 'Drops by unannounced with a find' },
      { key: 'takesSide', at: 'close', text: 'Puts in a good word with someone who is cross with you' },
      { key: 'stopsVisiting', at: 'cold', down: true, text: 'Stops coming round' },
    ],
    startWarmth: 45,
    startTrust: 35,
    listed: 'always',
  },
  {
    id: 'ines',
    name: 'Inès Belkacem',
    short: 'Inès',
    role: 'old friend (RPGs)',
    group: 'friends',
    whereabouts: 'Comes round some evenings; on the phone any time',
    intro: 'Inès. We’ve known each other since the lycée, idiot.',
    traits: ['collector', 'proud', 'nostalgic'],
    tastes: { platforms: ['snes', 'ps1'], genres: ['rpg', 'adventure', 'strategy'], era: [1992, 2001] },
    likes: ['record', 'game', 'flowers'],
    dislikes: ['scrap'],
    birthday: 26,
    look: { seed: 527, role: 'shopper' },
    phone: true,
    ties: { sam: 0.6, marco: 0.4, victor: -0.3 },
    facts: [
      { id: 'ff', text: 'Has finished Final Fantasy VII eleven times', says: 'Eleven times. And I cry every time. Every time.' },
      { id: 'travel', text: 'Travels for work and sends postcards', says: 'I’m in Osaka next month for work. I’ll send you a card. And a cartridge, if I find one.', from: 'friendly' },
    ],
    effects: [
      { key: 'lendsGames', at: 'friend', text: 'Lends you games from her own shelf' },
      { key: 'postcards', at: 'friendly', text: 'Sends postcards when she travels (sometimes with a game)' },
      { key: 'dropsBy', at: 'close', text: 'Drops by unannounced with a find' },
      { key: 'takesSide', at: 'close', text: 'Puts in a good word with someone who is cross with you' },
      { key: 'stopsVisiting', at: 'cold', down: true, text: 'Stops coming round' },
    ],
    startWarmth: 40,
    startTrust: 40,
    listed: 'always',
  },
  {
    id: 'marco',
    name: 'Marco Ferri',
    short: 'Marco',
    role: 'old friend (racing, fighting)',
    group: 'friends',
    whereabouts: 'Comes round some afternoons; on the phone any time',
    intro: 'Marco! Your favourite person. Don’t argue.',
    traits: ['competitive', 'funny', 'generous'],
    tastes: { platforms: ['megadrive', 'n64', 'ps1'], genres: ['racing', 'fighting', 'sports', 'shooter', 'beat'], era: [1990, 2000] },
    likes: ['croissant', 'coffee', 'game'],
    dislikes: ['flowers'],
    birthday: 41,
    look: { seed: 743, role: 'shopper' },
    phone: true,
    ties: { sam: 0.7, ines: 0.4 },
    facts: [
      { id: 'van', text: 'Has a van (and lends it)', says: 'I’ve got the van this week. Need anything moved? Sofa? Body? Kidding.' },
      { id: 'arcade', text: 'Holds the arcade’s Duel record (he says)', says: 'I hold the record on Duel at the arcade. Check the board. Okay, I held it.', from: 'friendly' },
    ],
    effects: [
      { key: 'helpsCarry', at: 'friendly', text: 'Brings his van: heavy furniture moved in one go' },
      { key: 'lendsGames', at: 'friend', text: 'Lends you games from his own shelf' },
      { key: 'arcadePartner', at: 'friend', text: 'Joins you at the arcade for two-player cabinets' },
      { key: 'dropsBy', at: 'close', text: 'Drops by unannounced with a find' },
      { key: 'stopsVisiting', at: 'cold', down: true, text: 'Stops coming round' },
    ],
    startWarmth: 45,
    startTrust: 30,
    listed: 'always',
  },
];
