import type { PersonCard, SocialEffect } from '../types';

/*
 * The flea market's stallholders (docs/economy.md "The finer market", docs/social.md "The market"): one per platform's
 * stall, id `stall-<platform>` (`social/market.stallPerson`). Their look's seed is the stall's (`furnishMarket`:
 * the stall's index + 1). What a regular gets and what an insulted one does are the same for all of them.
 */

/** Every stallholder's perks and penalties (read by `MarketStock` and the market's wiring through `social/market`). */
const STALL_EFFECTS: readonly SocialEffect[] = [
  { key: 'easierHaggle', at: 'friendly', text: 'Haggles more easily with you' },
  { key: 'keptAside', at: 'friend', text: 'Keeps a copy aside for you every market day' },
  { key: 'wishlistCall', at: 'friend', text: 'Rings you in the morning when a game off your wishlist comes in' },
  { key: 'credit', at: 'close', trust: 60, text: 'Gives you credit: coins now, paid back the next market day' },
  { key: 'noHaggle', at: 'cold', down: true, text: 'Won’t haggle with you' },
  { key: 'hidesBest', at: 'hostile', down: true, text: 'Keeps the showpiece out of your sight' },
  { key: 'markup', at: 'hostile', down: true, value: 1.05, text: 'Tags 5% higher for you' },
];

export const MARKET_STALL_PEOPLE: readonly PersonCard[] = [
  {
    id: 'stall-nes',
    name: 'Gérard Puech',
    short: 'Gégé',
    role: 'the NES stall',
    group: 'market',
    whereabouts: 'Behind the NES stall at the flea market, every market day',
    intro: 'Gérard. Everyone says Gégé. Grey cartridges since 1987, and I’ve blown into every one of them.',
    traits: ['nostalgic', 'chatty'],
    tastes: { platforms: ['nes'], era: [1985, 1992] },
    likes: ['croissant', 'coffee'],
    dislikes: ['flowers'],
    birthday: 8,
    look: { seed: 1, role: 'vendor' },
    phone: true,
    ties: { 'stall-snes': 0.4, 'stall-gb': 0.5, 'stall-megadrive': -0.2 },
    facts: [
      { id: 'shop', text: 'Had a games shop on Front Street until 2004', says: 'I had a shop, you know. Where the phone place is now. Twenty years.' },
      { id: 'blow', text: 'Swears blowing on cartridges works', says: 'Blowing on them works. Don’t let anyone tell you otherwise.', from: 'friendly' },
    ],
    effects: STALL_EFFECTS,
    lines: { hello: ['Ah, my favourite customer. Or one of them.', 'Morning! Grey and boxed, all of it.', 'You again! Good.'] },
  },
  {
    id: 'stall-snes',
    name: 'Yuki Tanaka',
    short: 'Yuki',
    role: 'the Super Nintendo stall',
    group: 'market',
    whereabouts: 'Behind the Super Nintendo stall at the flea market, every market day',
    intro: 'Tanaka. Yuki. Super Nintendo, PAL and imports. Please don’t bend the boxes.',
    traits: ['collector', 'proud', 'neat'],
    tastes: { platforms: ['snes'], genres: ['rpg'] },
    likes: ['record', 'cake'],
    dislikes: ['coins', 'scrap'],
    birthday: 19,
    look: { seed: 2, role: 'vendor' },
    phone: true,
    ties: { 'stall-nes': 0.4, 'stall-n64': 0.3, pettibone: -0.3 },
    facts: [
      { id: 'imports', text: 'Imports Super Famicom games from her cousin in Osaka', says: 'My cousin in Osaka sends me a box every month. I keep the best ones.' },
      { id: 'pettibone', text: 'Mrs Pettibone outbids her at every sale', says: 'Mrs Pettibone. Every sale. Every Super Nintendo lot. Every time.', from: 'friendly' },
    ],
    effects: STALL_EFFECTS,
    lines: { hello: ['Hello. Mind the boxes.', 'Good morning.', 'Ah. Welcome back.'] },
  },
  {
    id: 'stall-gb',
    name: 'Malik Haddou',
    short: 'Malik',
    role: 'the Game Boy stall',
    group: 'market',
    whereabouts: 'On the Game Boy blanket at the flea market, every market day',
    intro: 'Malik! Game Boy, Game Boy Color, the odd Game Gear if nobody’s looking. Batteries not included.',
    traits: ['funny', 'generous'],
    tastes: { platforms: ['gb'], genres: ['puzzle', 'rpg'] },
    likes: ['croissant', 'plush'],
    dislikes: ['record'],
    birthday: 34,
    look: { seed: 3, role: 'vendor' },
    phone: true,
    ties: { 'stall-nes': 0.5, 'stall-n64': 0.4 },
    facts: [
      { id: 'tetris', text: 'Holds a Tetris score he won’t shut up about', says: '999,999 on Tetris. On the train. Nobody saw it. It still counts.' },
      { id: 'kids', text: 'Teaches his kids on the Game Boy he had at their age', says: 'My daughter plays my old Game Boy now. Same scratches.', from: 'friendly' },
    ],
    effects: STALL_EFFECTS,
    lines: { hello: ['Hey hey! Pocket-sized joy, right here.', 'My friend!', 'Back for more?'] },
  },
  {
    id: 'stall-megadrive',
    name: 'Sandrine Oury',
    short: 'Sandrine',
    role: 'the Mega Drive stall',
    group: 'market',
    whereabouts: 'Behind the Mega Drive stall at the flea market, every market day',
    intro: 'Oury. Mega Drive. Blast processing, fair prices, no time-wasters.',
    traits: ['competitive', 'businesslike'],
    tastes: { platforms: ['megadrive'], genres: ['action', 'shooter'] },
    likes: ['coffee', 'coins'],
    dislikes: ['plush'],
    birthday: 51,
    look: { seed: 4, role: 'vendor' },
    phone: true,
    ties: { 'stall-nes': -0.2, haddad: 0.4, lenny: 0.3 },
    facts: [
      { id: 'champion', text: 'Won a Sonic speed contest in 1992', says: 'Regional Sonic champion, 1992. They gave me a jacket. I still have the jacket.' },
      { id: 'rania', text: 'Swaps rarities with Mrs Haddad from your building', says: 'Rania Haddad? We swap. She thinks she wins. She doesn’t.', from: 'friendly' },
    ],
    effects: STALL_EFFECTS,
    lines: { hello: ['Buying or browsing?', 'Morning.', 'You. Good. I’ve got new stock.'] },
  },
  {
    id: 'stall-n64',
    name: 'Kevin Rocher',
    short: 'Kev',
    role: 'the Nintendo 64 stall',
    group: 'market',
    whereabouts: 'On the Nintendo 64 risers at the flea market, every market day',
    intro: 'Kev! N64, the Rumble Paks, the Expansion Paks, the lot. Four controllers, four friends, that’s the rule.',
    traits: ['chatty', 'funny'],
    tastes: { platforms: ['n64'], genres: ['racing', 'shooter'] },
    likes: ['plush', 'croissant'],
    dislikes: ['flowers'],
    birthday: 2,
    look: { seed: 5, role: 'vendor' },
    phone: true,
    ties: { 'stall-gb': 0.4, 'stall-snes': 0.3, student: 0.3 },
    facts: [
      { id: 'goldeneye', text: 'Never lost at GoldenEye (Oddjob banned)', says: 'GoldenEye. Never lost. Oddjob is banned at my table, obviously.' },
      { id: 'van', text: 'Sleeps in his van on market days', says: 'I sleep in the van on market nights. It’s fine. It’s cosy. It’s fine.', from: 'friend' },
    ],
    effects: STALL_EFFECTS,
    lines: { hello: ['Alright! What are we playing?', 'There they are!', 'Hey, you!'] },
  },
  {
    id: 'stall-ps1',
    name: 'Agnès Laurent',
    short: 'Agnès',
    role: 'the PlayStation stall',
    group: 'market',
    whereabouts: 'Behind the PlayStation glass case at the flea market, every market day',
    intro: 'Agnès. PlayStation. The discs are checked, every one, under the lamp.',
    traits: ['shy', 'nostalgic', 'neat'],
    tastes: { platforms: ['ps1'], genres: ['rpg', 'adventure'] },
    likes: ['flowers', 'record'],
    dislikes: ['coins'],
    birthday: 45,
    look: { seed: 6, role: 'vendor' },
    phone: true,
    ties: { 'stall-snes': 0.3, ines: 0.3 },
    facts: [
      { id: 'lamp', text: 'Checks every disc under a jeweller’s lamp', says: 'I check every disc under my father’s jeweller’s lamp. Scratches tell stories.' },
      { id: 'ff', text: 'Cried at the end of Final Fantasy IX', says: 'The end of Final Fantasy IX. I don’t talk about it. Not here.', from: 'friend' },
    ],
    effects: STALL_EFFECTS,
    lines: { hello: ['Oh. Hello.', 'Hello again.', 'Good morning.'] },
  },
];
