import type { PersonCard } from '../types';

/*
 * Front Street, the flea market, the arcade, the saleroom (docs/economy.md): the people who sell, serve, play and
 * bid. Each card's `look.seed` is the seed their body is built with, so the book's portrait is the face met.
 */

export const STREET_PEOPLE: readonly PersonCard[] = [
  {
    id: 'lou',
    name: 'Lou Marchetti',
    short: 'Lou',
    role: 'barista, SUNNY SIDE CAFE',
    group: 'street',
    whereabouts: 'Behind the counter of the SUNNY SIDE CAFE, in its hours',
    intro: 'Lou. I make the coffee and I hear everything. Mostly the second thing.',
    traits: ['gossip', 'chatty', 'funny'],
    likes: ['flowers', 'record', 'croissant'],
    dislikes: ['coffee'],
    birthday: 3,
    look: { seed: 205, role: 'vendor' },
    phone: true,
    ties: { busker: 0.5, remi: 0.4, victor: -0.2 },
    facts: [
      { id: 'band', text: 'Plays bass in a band nobody has heard of', says: 'My band plays the Anchor on Thursdays. Nobody comes. It’s very exclusive.' },
      { id: 'victor', text: 'Knows Victor Crane’s habits', says: 'Victor has his espresso here at nine sharp, then the market. Like a clock.', from: 'friend' },
    ],
    effects: [
      { key: 'twoTips', at: 'friendly', text: 'Two market tips with the coffee instead of one' },
      { key: 'freeCoffee', at: 'friend', text: 'Your coffee is on the house, once a day' },
      { key: 'victorWhere', at: 'close', text: 'Tells you where Victor is headed today' },
      { key: 'noTip', at: 'cold', down: true, text: 'No market tip with the coffee' },
    ],
  },
  {
    id: 'remi',
    name: 'Rémi Okonkwo',
    short: 'Rémi',
    role: 'barista, PARKSIDE CAFE',
    group: 'street',
    whereabouts: 'Behind the counter of the PARKSIDE CAFE, in its hours',
    intro: 'Rémi. Lou trained me. Don’t tell her my flat white is better.',
    traits: ['shy', 'neat', 'earlyBird'],
    likes: ['record', 'cake'],
    dislikes: ['scrap'],
    birthday: 39,
    look: { seed: 206, role: 'vendor' },
    ties: { lou: 0.4 },
    facts: [{ id: 'park', text: 'Feeds the park’s pigeons every closing time', says: 'At closing I give the pigeons the crusts. They wait on the railing. Every day.' }],
    effects: [
      { key: 'twoTips', at: 'friendly', text: 'Two market tips with the coffee instead of one' },
      { key: 'freeCoffee', at: 'friend', text: 'Your coffee is on the house, once a day' },
      { key: 'noTip', at: 'cold', down: true, text: 'No market tip with the coffee' },
    ],
  },
  {
    id: 'busker',
    name: 'Django Ferreira',
    short: 'Django',
    role: 'the busker',
    group: 'street',
    whereabouts: 'By the bus shelter on Front Street, by day, when it is dry',
    intro: 'Django. Like the guitarist, but with a keyboard from 1986. Requests are a coin. Or a croissant.',
    traits: ['funny', 'nostalgic', 'generous'],
    likes: ['croissant', 'coins', 'record'],
    birthday: 46,
    look: { seed: 277, role: 'shopper' },
    ties: { lou: 0.5 },
    facts: [{ id: 'tape', text: 'Records his tunes on cassette, and presses the odd one on vinyl', says: 'I put my tunes on tape. And once a year a friend presses one on vinyl. Hiss included at no extra cost.', from: 'friendly' }],
    effects: [
      { key: 'favouriteTune', at: 'friendly', text: 'Strikes up your most requested tune when you come by' },
      { key: 'freeRequests', at: 'friend', text: 'Your requests are free' },
      { key: 'tape', at: 'close', text: 'Gives you a record of his for the turntable (once)' },
    ],
  },
  {
    id: 'clerk-furniture',
    name: 'Bernard Valette',
    short: 'Bernard',
    role: 'SECOND HOME, the furniture shop',
    group: 'street',
    whereabouts: 'In SECOND HOME, in its hours',
    intro: 'Bernard. Every chair in here has had a life before. Like me.',
    traits: ['businesslike', 'neat'],
    likes: ['coffee', 'coins'],
    birthday: 11,
    look: { seed: 71, role: 'vendor' },
    effects: [
      { key: 'discount', at: 'friendly', value: 0.95, text: '5% off everything in the shop' },
      { key: 'discount', at: 'friend', value: 0.9, text: '10% off everything in the shop' },
      { key: 'discount', at: 'close', value: 0.85, text: 'Trade price for you: 15% off' },
      { key: 'markup', at: 'cold', down: true, value: 1.05, text: 'Prices 5% higher for you' },
      { key: 'markup', at: 'hostile', down: true, value: 1.1, text: 'Prices 10% higher for you' },
    ],
  },
  {
    id: 'clerk-tv',
    name: 'Karim Benali',
    short: 'Karim',
    role: 'TV REPAIR',
    group: 'street',
    whereabouts: 'In TV REPAIR, in its hours',
    intro: 'Karim. If it has a tube, I can fix it. If it has an app, go away.',
    traits: ['collector', 'grumpy'],
    tastes: { platforms: ['nes', 'megadrive', 'snes'] },
    likes: ['coffee', 'game'],
    dislikes: ['flowers'],
    birthday: 33,
    look: { seed: 83, role: 'vendor' },
    effects: [
      { key: 'discount', at: 'friendly', value: 0.95, text: '5% off everything in the shop' },
      { key: 'repairTips', at: 'friend', text: 'Talks you through the console on your kitchen table' },
      { key: 'discount', at: 'close', value: 0.85, text: 'Trade price for you: 15% off' },
      { key: 'markup', at: 'cold', down: true, value: 1.05, text: 'Prices 5% higher for you' },
      { key: 'markup', at: 'hostile', down: true, value: 1.1, text: 'Prices 10% higher for you' },
    ],
  },
  {
    id: 'clerk-pets',
    name: 'Nadia Costa',
    short: 'Nadia',
    role: 'PAWS & CLAWS, the pet shop',
    group: 'street',
    whereabouts: 'In the pet shop, in its hours',
    intro: 'Nadia. If you have a cat, you have a boss. I just sell the boss things.',
    traits: ['catPerson', 'chatty', 'generous'],
    likes: ['flowers', 'cake', 'plush'],
    birthday: 15,
    look: { seed: 97, role: 'vendor' },
    effects: [
      { key: 'discount', at: 'friendly', value: 0.95, text: '5% off everything in the shop' },
      { key: 'freeTreats', at: 'friend', text: 'A free pouch of treats, once a day' },
      { key: 'catAdvice', at: 'close', text: 'Reads your cat for you: what it wants' },
      { key: 'markup', at: 'cold', down: true, value: 1.05, text: 'Prices 5% higher for you' },
      { key: 'markup', at: 'hostile', down: true, value: 1.1, text: 'Prices 10% higher for you' },
    ],
  },
  {
    id: 'clerk-florist',
    name: 'Iris Moreno',
    short: 'Iris',
    role: 'the florist',
    group: 'street',
    whereabouts: 'In the florist’s, in its hours',
    intro: 'Iris. Yes, like the flower. My mother had one joke.',
    traits: ['romantic', 'shy'],
    likes: ['record', 'croissant', 'cake'],
    dislikes: ['flowers'],
    birthday: 22,
    look: { seed: 59, role: 'vendor' },
    effects: [
      { key: 'discount', at: 'friendly', value: 0.95, text: '5% off everything in the shop' },
      { key: 'extraBunch', at: 'friend', value: 4, text: 'Four bunches for the price of two' },
      { key: 'markup', at: 'cold', down: true, value: 1.05, text: 'Prices 5% higher for you' },
      { key: 'markup', at: 'hostile', down: true, value: 1.1, text: 'Prices 10% higher for you' },
    ],
  },
];

export const ARCADE_PEOPLE: readonly PersonCard[] = [
  {
    id: 'attendant',
    name: 'Gus Lemaire',
    short: 'Gus',
    role: 'the arcade’s attendant',
    group: 'arcade',
    whereabouts: 'At the prize counter of the arcade',
    intro: 'Gus. I run the counter, I fix the claw, I hear the claw is rigged. It is not. Much.',
    traits: ['businesslike', 'funny'],
    likes: ['coffee', 'croissant'],
    birthday: 29,
    look: { seed: 5, role: 'vendor' },
    ties: { kid: 0.6, rossi: 0.3 },
    effects: [
      { key: 'freeCredit', at: 'friendly', value: 1, text: 'A free credit, once a day' },
      { key: 'insider', at: 'friend', text: 'Tells you what is good today: the challenge, the jackpot, the machine to avoid' },
      { key: 'freeCredit', at: 'close', value: 2, text: 'Two free credits a day' },
      { key: 'noChange', at: 'cold', down: true, text: 'The change machine is “out of order” for you' },
    ],
  },
  {
    id: 'kid',
    name: 'Nico',
    short: 'Nico',
    role: 'the kid at the arcade',
    group: 'arcade',
    whereabouts: 'At the arcade after school, watching',
    intro: 'I’m Nico. I’m not supposed to be here. Are you any good?',
    traits: ['competitive', 'chatty'],
    likes: ['plush', 'croissant'],
    dislikes: ['flowers', 'coins'],
    birthday: 50,
    look: { seed: 223, role: 'shopper' },
    ties: { attendant: 0.6 },
    effects: [
      { key: 'cheers', at: 'friendly', text: 'Cheers louder when you play' },
      { key: 'doubles', at: 'friend', value: 5, text: 'Your corner at the Saturday tournament: 5 tickets from the regulars’ whip-round for every round you win' },
      { key: 'playerTwo', at: 'close', text: 'Comes over to watch every game, and always takes player two' },
      { key: 'heckles', at: 'cold', down: true, text: 'Heckles you while you play, and won’t take player two' },
    ],
  },
];

export const MARKET_PEOPLE: readonly PersonCard[] = [
  {
    id: 'albers',
    name: 'Ingrid Albers',
    short: 'Mrs Albers',
    role: 'the collectors’ club',
    group: 'market',
    whereabouts: 'Visits when an honour is completed',
    intro: 'Ingrid Albers, the collectors’ club. We keep an eye on the serious ones.',
    traits: ['collector', 'proud', 'businesslike'],
    likes: ['record', 'game'],
    birthday: 18,
    look: { seed: 4707, role: 'shopper' },
    ties: { victor: 0.2, okafor: 0.4 },
    effects: [{ key: 'clubBonus', at: 'friend', value: 1.25, text: 'The club’s gifts are a quarter larger' }],
  },
];

export const RIVAL_PEOPLE: readonly PersonCard[] = [
  {
    id: 'victor',
    name: 'Victor Crane',
    short: 'Victor',
    role: 'the rival collector',
    group: 'rivals',
    whereabouts: 'The flea market some mornings, the saleroom’s front row, outside RETRO GAMES one day in three',
    intro: 'Victor Crane. You will have heard of me. If not, you will.',
    traits: ['competitive', 'proud', 'collector'],
    likes: ['record', 'game', 'coffee'],
    dislikes: ['plush', 'flowers', 'coins'],
    birthday: 55,
    look: { seed: 911, role: 'shopper' },
    phone: true,
    ties: { haddad: -0.4, lou: -0.2, albers: 0.2 },
    facts: [
      { id: 'father', text: 'Inherited his father’s collection at nineteen', says: 'My father collected. I inherited eleven thousand games and an opinion of myself.', from: 'friendly' },
      { id: 'lonely', text: 'Has nobody to show his collection to', says: 'Do you know how many people have seen my collection? Two. One was the insurer.', from: 'friend' },
    ],
    effects: [
      { key: 'snipesWishlist', at: 'hostile', down: true, text: 'Goes after the games on your wishlist on purpose' },
      { key: 'spiteBids', at: 'nemesis', down: true, text: 'Bids against you at the saleroom out of spite' },
      { key: 'duplicatesAtCost', at: 'friendly', text: 'Sells you his duplicates at cost' },
      { key: 'splitLots', at: 'friend', trust: 35, text: 'Offers to split a saleroom lot with you' },
      { key: 'showsCollection', at: 'close', text: 'Shows you his collection' },
    ],
    startWarmth: -10,
    startTrust: 10,
    lines: {
      hello: ['Ah. You.', 'Still collecting, I see.', 'Morning.'],
      chat: ['The market is not what it was. Too many people who know what things are worth. Present company included.', 'I had breakfast with a man who owns two sealed Stadium Events. Two. Unbearable.'],
      talkGames: ['Now that is a question for someone who knows. Sit down, this will take a while.', 'You’ve got taste. Infuriating, but there it is.'],
      compliment: ['…Thank you. Nobody says that. They say “how much”.', 'Flattery. Effective flattery, I grant you.'],
      challenge: ['A wager? Next market day, first to the star copy. Loser buys the espresso.'],
      cold: ['I’m busy.'],
      hostile: ['Out of my light.'],
    },
  },
  {
    id: 'doris',
    name: 'Doris Pell',
    short: 'Doris',
    role: 'saleroom regular (impulsive)',
    group: 'rivals',
    whereabouts: 'The saleroom, every sale',
    intro: 'Doris! I come for the excitement. I end up with the furniture.',
    traits: ['chatty', 'romantic', 'generous'],
    likes: ['flowers', 'cake'],
    birthday: 1,
    look: { seed: 431, role: 'shopper' },
    ties: { okafor: 0.3, pettibone: 0.5 },
    effects: [
      { key: 'dropsOut', at: 'friend', text: 'Drops out when you bid on a lot she knows you want' },
      { key: 'tradePrice', at: 'close', text: 'Sells you what she got carried away on, at what she paid' },
    ],
    lines: { chat: ['Ooh, I do love a sale. My grandson says I get carried away.', 'If I like it, I bid. Life is short, dear.', 'I bought a Virtual Boy here once. Never again. Well, maybe.'] },
  },
  {
    id: 'okafor',
    name: 'Emeka Okafor',
    short: 'Mr Okafor',
    role: 'saleroom regular (the sniper)',
    group: 'rivals',
    whereabouts: 'The saleroom, the back row',
    intro: 'Okafor. I bid late and I bid once.',
    traits: ['businesslike', 'proud'],
    likes: ['coffee', 'record'],
    birthday: 40,
    look: { seed: 437, role: 'shopper' },
    ties: { albers: 0.4, lenny: -0.3 },
    effects: [
      { key: 'dropsOut', at: 'friend', text: 'Drops out when you bid on a lot he knows you want' },
      { key: 'starLotTip', at: 'close', text: 'Tells you the star lot before the sale' },
    ],
    lines: { chat: ['Patience. The bargains are made on "going twice".', 'I never show my hand before the auctioneer has to.', 'Watch the clock, not the room.'] },
  },
  {
    id: 'pettibone',
    name: 'Margaret Pettibone',
    short: 'Mrs Pettibone',
    role: 'saleroom regular (Super Nintendo, stubborn)',
    group: 'rivals',
    whereabouts: 'The saleroom, for Super Nintendo lots',
    intro: 'Pettibone. Super Nintendo, young man, young woman, whatever you are. Nothing else.',
    traits: ['proud', 'nostalgic', 'collector'],
    tastes: { platforms: ['snes'] },
    likes: ['cake', 'game'],
    birthday: 12,
    look: { seed: 443, role: 'shopper' },
    ties: { doris: 0.5 },
    effects: [
      { key: 'dropsOut', at: 'friend', text: 'Lets a Super Nintendo lot go when you want it' },
      { key: 'starLotTip', at: 'close', text: 'Tells you the star lot before the sale' },
    ],
    lines: { chat: ['Super Nintendo, young one. Everything else is a fad.', 'I have every PAL Super Nintendo game but eleven. Ten, after today.', 'Outbid me on a Super Nintendo game and I will remember your face.'] },
  },
  {
    id: 'lenny',
    name: 'Lenny Shaw',
    short: 'Lenny',
    role: 'saleroom regular (the dealer)',
    group: 'rivals',
    whereabouts: 'The saleroom, by the door',
    intro: 'Lenny. Trade only, mate. Nothing personal.',
    traits: ['businesslike', 'funny'],
    likes: ['coins', 'coffee'],
    birthday: 36,
    look: { seed: 449, role: 'shopper' },
    ties: { okafor: -0.3 },
    effects: [
      { key: 'dropsOut', at: 'friend', text: 'Drops out when you bid on a lot he knows you want' },
      { key: 'tradePrice', at: 'close', text: 'Sells you a lot at trade price after the sale' },
    ],
    lines: { chat: ['Trade only, mate. I buy to sell, so I know my ceiling.', 'Whatever I pay here, I need double on my stall.', 'Bid me up if you like. I stop where the money stops.'] },
  },
];
